### ISSUE TITLE
after updating firebase-messaging to 22.0.0, new installs crash during first boot (only on first boot)

### ISSUE THREAD

**Issue by lwky** [Pushwoosh/pushwoosh-android-sdk#169]
Where can I find which firebase-bom I should use for each version of the pushwoosh sdk?

using:
```
implementation 'com.pushwoosh:pushwoosh:6.3.0'
implementation 'com.pushwoosh:pushwoosh-firebase:6.3.0'`

implementation platform('com.google.firebase:firebase-bom:28.3.1')
implementation 'com.google.firebase:firebase-messaging' //version 22.0.0 from firebase-bom
```

> java.lang.NoSuchMethodError: getToken() method not found. Most likely that the current version of 'com.google.firebase:firebase-messaging' library is not supported by Pushwoosh yet. Contact Pushwoosh support for more information.

```
E AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
E AndroidRuntime: Process: xx.xxxxx.xxxxxx, PID: 32656
E AndroidRuntime: java.lang.NoSuchMethodError: getToken() method not found. Most likely that the current version of 'com.google.firebase:firebase-messaging' library is not supported by Pushwoosh yet. Contact Pushwoosh support for more information.
E AndroidRuntime: 	at com.pushwoosh.firebase.a.d.a.b()
E AndroidRuntime: 	at com.pushwoosh.firebase.a.d.a.d()
E AndroidRuntime: 	at com.pushwoosh.firebase.PushwooshFcmHelper.onTokenRefresh()
E AndroidRuntime: 	at com.pushwoosh.firebase.PushFcmIntentService.onNewToken()
E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@22.0.0:4)
E AndroidRuntime: 	at com.google.firebase.messaging.g.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@22.0.0:1)
E AndroidRuntime: 	at com.google.firebase.messaging.d.run(com.google.firebase:firebase-messaging@@22.0.0)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E AndroidRuntime: 	at com.google.android.gms.common.util.q.b.run(Unknown Source)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
E AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
D AppTracker: App Event: crash
E AbstractTracker: mTrackerAsyncQueryHandler is null
W ActivityManager:   Force finishing activity
```

**Comment by wfhm** [comment]
Hi @lwky,

I could reproduce the issue neither with the 28.3.1 version of firebase-bom nor with firebase-messaging:22.0.0. Can you please share the entire build.gradle file?

**Comment by lwky** [comment]
Hi wfhm,
running on a device with api23

```
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath 'com.google.gms:google-services:4.3.8'
	classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
    }
}
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" } 
    }
}
```

***
v6.2.7
```
implementation platform('com.google.firebase:firebase-bom:27.0.0')
implementation 'com.google.firebase:firebase-analytics'
implementation 'com.google.firebase:firebase-crashlytics-ndk'
implementation "com.android.support:appcompat-v7:27.1.1"
implementation 'com.pushwoosh:pushwoosh:6.2.7'
implementation 'com.pushwoosh:pushwoosh-firebase:6.2.7'
implementation 'com.google.firebase:firebase-messaging' //21.1.0 from bom 27.0.0
```
works

***
v6.3.0
```
implementation platform('com.google.firebase:firebase-bom:27.0.0')
implementation 'com.google.firebase:firebase-analytics'
implementation 'com.google.firebase:firebase-crashlytics-ndk'
implementation "com.android.support:appcompat-v7:27.1.1
implementation 'com.pushwoosh:pushwoosh:6.3.0'
implementation 'com.pushwoosh:pushwoosh-firebase:6.3.0'
implementation 'com.google.firebase:firebase-messaging' //21.1.0 from bom 27.0.0
```
no push token, this error in logcat:
```Pushwoosh: [PushwooshFcmHelper] FCM registration error:getInstance []```

***
v6.3.0
```
implementation platform('com.google.firebase:firebase-bom:28.3.1')
implementation 'com.google.firebase:firebase-analytics'
implementation 'com.google.firebase:firebase-crashlytics-ndk'
implementation "com.android.support:appcompat-v7:27.1.1
implementation 'com.pushwoosh:pushwoosh:6.3.0'
implementation 'com.pushwoosh:pushwoosh-firebase:6.3.0'
implementation 'com.google.firebase:firebase-messaging' //22.0.0 from bom 28.3.1
```
crash on first boot with this error:
```
  E AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
  E AndroidRuntime: Process: com.magneds.it.lidl.freshheads.test, PID: 23425
  E AndroidRuntime: java.lang.NoSuchMethodError: getToken() method not found. Most likely that the current version of 'com.google.firebase:firebase-messaging' library is not supported by Pushwoosh yet. Contact Pushwoosh support for more information.
  E AndroidRuntime: 	at com.pushwoosh.firebase.a.d.a.b()
  E AndroidRuntime: 	at com.pushwoosh.firebase.a.d.a.d()
  E AndroidRuntime: 	at com.pushwoosh.firebase.PushwooshFcmHelper.onTokenRefresh()
  E AndroidRuntime: 	at com.pushwoosh.firebase.PushFcmIntentService.onNewToken()
  E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@22.0.0:4)
  E AndroidRuntime: 	at com.google.firebase.messaging.g.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@22.0.0:1)
  E AndroidRuntime: 	at com.google.firebase.messaging.d.run(com.google.firebase:firebase-messaging@@22.0.0)
  E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  E AndroidRuntime: 	at com.google.android.gms.common.util.q.b.run(Unknown Source)
  E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```
on second run, the app does not crash but the error keeps showing up in logcat, this time thrown by `WM-WorkerWrapper` instead of `AndroidRuntime`

**Comment by k-kagurazaka** [comment]
I had the same issue and solved by adding following rules into `proguard-rules.pro`

```
-keep public class com.google.firebase.messaging.FirebaseMessaging {
    public *;
}
```

**Comment by wfhm** [comment]
@lwky still no luck reproducing the issue with firebase-bom:28.3.1, tried on a device with API 23 as well - still the same result. By any chance can you share a simple reproducer project with us?

**Comment by kvn-stgl** [comment]
I have the same problem. But it's only for release builds with `isMinifyEnabled = true`. So it's probably a problem with the proguard configuration. 

For a dirty workaround I put the following line into my proguard rules: `-keep class com.google.firebase.messaging.** { *; }`

**Comment by wfhm** [comment]
@lwky @kvn-stgl got it reproduced, will be fixed with the next release.

**Comment by wfhm** [comment]
@lwky @kvn-stgl Fixed with 6.3.1.
